version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"  # Maps container port 8000 to host port 8000
    command: python manage.py runserver 0.0.0.0:8000  # Listen on all interfaces
    volumes:
      - .:/app
    environment:
      - DEBUG=True

