# Generated by Django 5.1.4 on 2024-12-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealzoapp', '0002_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='restaurant_name',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='account_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_hours',
            field=models.CharField(max_length=100),
        ),
    ]
