# Generated by Django 5.1.4 on 2024-12-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealzoapp', '0003_rename_name_restaurant_restaurant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='static/images/pan_cards/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/restaurant_photos/'),
        ),
    ]
