# Generated by Django 5.1.4 on 2024-12-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealzoapp', '0004_alter_restaurant_pan_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('adhar_card', models.FileField(blank=True, null=True, upload_to='static/documents/adhar_cards/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='static/documents/pan_cards/')),
                ('driving_license', models.FileField(blank=True, null=True, upload_to='static/documents/driving_licenses/')),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='static/documents/vehicle_registration/')),
                ('insurance', models.FileField(blank=True, null=True, upload_to='static/documents/vehicle_insurance/')),
                ('license_number', models.CharField(max_length=20)),
            ],
        ),
    ]
